name: Build Windows Package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild for VS 2019
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[16.0, 17.0)' # Targets VS 2019 (version 16.x)
      
    - name: Enable Long Paths
      run: |
          git config --system core.longpaths true
          reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f
  
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: 3.24.5
        architecture: x64
    - name: Install Flutter dependencies
      run: flutter pub get
    - name: Enable Windows support
      run: flutter config --enable-windows-desktop
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13
    - name: Run Windows Build Script
      run: python3 windows/build_windows.py
      
    # - name: Extract Version from pubspec.yaml
    #   run: |
    #     # Extract the version from pubspec.yaml
    #     VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
    #     echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-package
        path: build/windows/PicaComic-4.0.4-windows-installer.exe
